//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use super::sea_orm_active_enums::DiscordSourceType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "discord_source")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub discord_source_id: Uuid,
    pub server_name: String,
    pub channel_name: String,
    pub discord_server_id: i64,
    pub discord_channel_id: i64,
    pub is_active: bool,
    pub source_type: DiscordSourceType,
    pub source_config: Json,
    pub last_swept_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
