//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "discord_source_type"
)]
pub enum DiscordSourceType {
    #[sea_orm(string_value = "bot")]
    Bot,
    #[sea_orm(string_value = "none")]
    None,
    #[sea_orm(string_value = "roleplay")]
    Roleplay,
}
